# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.cache/wt [current_project]
set_property parent.project_path C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/lenovo/Desktop/Manual-Merged/SEU_CSE_507_user_uart_bmpg_1.3 [current_project]
set_property ip_output_repo c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/alu.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/control.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/cpu_clk.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/data_memory.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/dma.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/instruction_fetch.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/instruction_memory.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/interrupt_encoder.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/io.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/keyboard.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/register.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/seg.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/sign_extension.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/stabilizer.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/sys_clock.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/uart.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/vic.v
  C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/new/cpu_top.v
}
read_ip -quiet c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/uart_bmpg_0/uart_bmpg_0.xci

read_ip -quiet c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/RAM_d_64K/RAM_d_64K.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/RAM_d_64K/RAM_d_64K_ooc.xdc]

read_ip -quiet c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/RAM_i_64K/RAM_i_64K.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/RAM_i_64K/RAM_i_64K_ooc.xdc]

read_ip -quiet c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/cpu_wiz_clk/cpu_wiz_clk.xci
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/cpu_wiz_clk/cpu_wiz_clk_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/cpu_wiz_clk/cpu_wiz_clk.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/sources_1/ip/cpu_wiz_clk/cpu_wiz_clk_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/lenovo/Desktop/Manual-Merged/Manual-Merged.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top cpu_top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb"
