# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/uart_bmpg_0/uart_bmpg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_bmpg_0 || ORIG_REF_NAME==uart_bmpg_0} -quiet] -quiet

# IP: ip/RAM_d_64K/RAM_d_64K.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_d_64K || ORIG_REF_NAME==RAM_d_64K} -quiet] -quiet

# IP: ip/RAM_i_64K/RAM_i_64K.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_i_64K || ORIG_REF_NAME==RAM_i_64K} -quiet] -quiet
