# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/GitHub/Artanisax/CS214-Minisys-CPU/src/CS214-Minisys-CPU.srcs/sources_1/ip/RAM_64K/RAM_64K.xci
# IP: The module: 'RAM_64K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub/Artanisax/CS214-Minisys-CPU/src/CS214-Minisys-CPU.srcs/sources_1/ip/RAM_64K/RAM_64K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_64K'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/GitHub/Artanisax/CS214-Minisys-CPU/src/CS214-Minisys-CPU.srcs/sources_1/ip/RAM_64K/RAM_64K.xci
# IP: The module: 'RAM_64K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub/Artanisax/CS214-Minisys-CPU/src/CS214-Minisys-CPU.srcs/sources_1/ip/RAM_64K/RAM_64K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_64K'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
